FROM ubuntu:bionic

# Install Supervisor, Node.js and NPM
RUN apt-get update && \
    apt-get install -y supervisor nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create logs folder
RUN mkdir -p /var/log/webhook

COPY http.js /srv/http.js
COPY webhooks.conf /etc/supervisor/conf.d/webhooks.conf
COPY entrypoint.sh /tmp/entrypoint.sh

ENTRYPOINT [ "/tmp/entrypoint.sh" ]
