FROM ubuntu:xenial

# Install Supervisor, Node.js, NPM and Ansible
RUN apt-get update && \
    apt-get install -y software-properties-common supervisor nodejs npm && \
    add-apt-repository --yes --update ppa:ansible/ansible  && \
    apt-get update && \
    apt-get install -y ansible && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create logs folder
RUN mkdir -p /var/log/webhook

COPY http.js /srv/http.js
COPY webhooks.conf /etc/supervisor/conf.d/webhooks.conf
COPY ansible-restarted-state.yaml /tmp/ansible-restarted-state.yaml
COPY ansible-restarted-stopped-started.yaml /tmp/ansible-restarted-stopped-started.yaml
COPY entrypoint.sh /tmp/entrypoint.sh

ENTRYPOINT [ "/tmp/entrypoint.sh" ]
